version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: postgres_easycab
    environment:
      POSTGRES_DB: easycab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      easycab_network:
        ipv4_address: 192.168.100.100
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ec_central:
    build:
      context: .
      dockerfile: ./EC_Central/Dockerfile
    image: ec-central:latest
    environment:
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5050
      SPRING_APPLICATION_NAME: EC_Central
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.100.100:5432/easycab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP-SERVERS: 192.168.100.3:9092
      SERVER_PORT: 8081
      BROKER_ADDRESS: 192.168.100.3:9092
      CTC_URL: http://192.168.100.200:8082/traffic
    ports:
      - "8081:8081"
      - "9090:9090"
    networks:
      easycab_network:
        ipv4_address: 192.168.100.4
      shared-network: {}
    depends_on:
      - postgres
  ec_ctc:
    container_name: ec_ctc
    build:
      context: .
      dockerfile: ./EC_CTC/Dockerfile
    image: ec-ctc:latest
    environment:
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5050
      SPRING_APPLICATION_NAME: EC_CTC
    ports:
      - "8082:8082"
    networks:
      - easycab_network
      - shared-network
    depends_on:
      - ec_central
  nginx:
    build:
      context: ./taxi-tracker-nginx
      dockerfile: Dockerfile
    container_name: taxi-tracker-nginx
    ports:
      - "8080:80"
    networks:
      easycab_network:
        ipv4_address: 192.168.100.14
    depends_on:
      - ec_central

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      shared-network:
        ipv4_address: 192.168.101.9

  logstash:
    image: logstash:8.9.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5050:5000"
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      shared-network:
        ipv4_address: 192.168.101.10

  kibana:
    image: kibana:8.9.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      shared-network:
        ipv4_address: 192.168.101.11
volumes:
  postgres_data:
  server:
  shared:
  client:
  esdata:

networks:
  easycab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  shared-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
