version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      easycab_network:
        ipv4_address: 192.168.100.2

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.100.3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: 192.168.100.2:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      easycab_network:
        ipv4_address: 192.168.100.3

  ec_customer_a:
    build:
      context: .
      dockerfile: ./EC_Customer/Dockerfile
    image: ec-customer-a:latest
    container_name: ec_customer_a
    environment:
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5050
      SPRING_APPLICATION_NAME: EC_Customer_a
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 192.168.100.3:9092
      CLIENT_ID: "a"
      broker.address: 192.168.100.3:9092
      file: destinations1.txt
    ports:
      - "9001:8080"
    depends_on:
      - kafka
    networks:
      - shared-network
      - easycab_network

#  ec_customer_b:
#    build:
#      context: .
#      dockerfile: ./EC_Customer/Dockerfile
#    image: ec-customer-b:latest
#    container_name: ec_customer_b
#    environment:
#      SPRING_APPLICATION_NAME: EC_Customer_b
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: 192.168.1.3:9092
#      CLIENT_ID: "b"
#      broker.address: 192.168.1.3:9092
#      file: destinations2.txt
#    ports:
#      - "9002:8080"
#    depends_on:
#      - kafka
#    networks:
#      easycab_network:
#        ipv4_address: 192.168.1.5
networks:
  easycab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  shared-network:
    external: true